U = 10.0
T = 1.0
pumpA = 0.0
probeA = 0.0
mu = 0
v_0 = 1
tmax = 5
dt = 0.001
dw = 0.005
tol = 0.001
solver = 0
fermion = 0
phonon = 0
Lambda = 0.0
wC = 50
t_diss_end = 100.0
pumpOmega = 10.0
t_pump_start = 0.0
t_pump_end = 100.0
probeOmega = 0.0
t_probe_start = 0.0
t_probe_end = 100.0
lattice_structure = 1
