
U = 5.0
Uconst = 5.0
T = 1.0
pumpA = 0.0
probeA = 0.0
mu = 0
v_0 = 1
tmax = 5
dt = 0.01
dw = 0.01
tol = 0.001
solver = 0
fermion = 1
phonon = 0
Lambda = 0.5
t_diss_end = 15.0
pumpOmega = 0.0
t_pump_start = 2.0
t_pump_end = 15.0
probeOmega = 0.0
t_probe_start = 5.0
t_probe_end = 15.0

